Capstone-Project
Joaquin123455/capstone-project pull request #1
Opened 2023-04-28 15:16 UTC by Joaquin123455

### General requirements

- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Make sure that you used correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

### HTML/CSS & JavaScript requirements

- Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- Follow our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

### Project requirements

- You should personalize the content of your page. Choose a topic that is different than the one in the original design.
- You should follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:
  - Colors.
  - Typography: font face, size and weight (we suggest using [Lato](https://www.latofonts.com/) as it is a free font similar to the one used in the original design).
  - Layout: composition and space between elements.
- The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable.
- You can use a CSS framework (for example Bootstrap) for styling, if you want to.
- You should build only these 2 pages:
  - The *home page*.
  - The *about page*.
- Each of these pages should have versions for 2 different screen sizes: 
  - Mobile: up to 768px wide.
  - Desktop: 768px or wider.

- Interactions
  - Links
    - The *home page* should have a link in the menu to the *about page*.
    - The logo in the header links to the *home page*.
  - Mobile menu
    - When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
    - There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design (colors, typography, spacings, etc.).
    - The mobile menu should have a close (X) button that closes the menu.
- Dynamic page
  - The section "Featured speakers" should be created dynamically in JavaScript.
  - You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.

Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

2023-04-28 21:13 UTC, V-Blaze requested changes
## Hi @Joaquin123455  , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![giphy](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Read me looks professional ✔
-  Meaningful commit message 👋 
-  Project deployed correctly ✔

 ## Required Changes ♻️
## You have done a great job so far, You have put in a great effort :+1: :+1: :100: , But following the project requirement is a requirement for this milestone. I'll go through the requirement and also the given design carefully and update your project appropriately.

- [ ] You did great adding a pull request summary, But following the best practice, A pull request summary should be a brief point and list of all the features you added to the current branch and not the full project requirement you were given, I'll greatly advice you edith your pull request description and add an eye-catching summary. :smile: :+1: :100: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 21:13 UTC, V-Blaze commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] According to the project requirement, you are supposed to make a 5 mins video following the instructions also listed. But I cant seem to find the video in your project summary or readme file. I'll suggest you follow the instructions and make the project demo video as required:

> Once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:
A description of the project.
A demo of the project features (different pages and different screen sizes).
You should also highlight some interesting piece of code or something you built that you are very proud of.
For recording the video you can use tools like [Loom](https://www.loom.com/) that let you share a private link to the recording, and configure a shot that shows your computer screen and your face at the same time in a small picture.

Add the video link to your pull request description.

2023-04-28 21:13 UTC, V-Blaze commented on index.html
> +    </nav>
- [ ] You did great implementing the nav bar. :+1: :+1: , But according to the project requirement, You are required to follow the given design, both the color, layout, and margins, You should only personalize the content.
> You should personalize the content of your page. Choose a topic that is different than the one in the original design.
You should follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:
Colors.
Typography: font face, size and weight (we suggest using [Lato](https://www.latofonts.com/) as it is a free font similar to the one used in the original design).
Layout: composition and space between elements.

- [ ] I'll suggest you follow the requirement strictly and make sure your project follows the given design. :smile: :+1:  This shows your ability to implement a given design which is a great skill to have :waffle: 

YOUR NAV BAR:
![Screenshot from 2023-04-28 21-38-53](https://user-images.githubusercontent.com/107632780/235250189-54fbda7a-7815-4491-b569-cac5b93c29be.png)

PROVIDED DESIGN:
![Screenshot from 2023-04-28 21-38-21](https://user-images.githubusercontent.com/107632780/235250314-8bbc9572-2677-4e7d-bce3-dadccd2c957b.png)

2023-04-28 21:13 UTC, V-Blaze commented on index.html
> +    </section>
- [ ] Just as I have suggested above, Following the given design is a crucial part of the requirement for this project. Please go through the design one more time and update each color and spacing. Remember to include any background color or image present in the given design

Your design:
![Screenshot from 2023-04-28 21-43-04](https://user-images.githubusercontent.com/107632780/235251132-1f691870-3245-4c1a-b5bf-dd452c89abfa.png)

Given design:
![Screenshot from 2023-04-28 21-43-25](https://user-images.githubusercontent.com/107632780/235251205-8952e37d-df3f-467a-90bf-52b03bac124d.png)

2023-04-28 21:13 UTC, V-Blaze commented on index.html
> +        <div class="activity">
- [ ] You did great adding the program section and also personalizing the content, But o think you need to make some UI design adjustments to match the given design, Your subheading color does not match the given design. Also, your button design should follow the provided template. I'll suggest you look into this and  make it look as required :+1: :100: 

YOUR CURRENT DESIGN:
![Screenshot from 2023-04-28 21-47-29](https://user-images.githubusercontent.com/107632780/235251894-3f106b65-fced-42fd-b483-53322ae0ecf7.png)

PROVIDED DESIGN:
![Screenshot from 2023-04-28 21-46-54](https://user-images.githubusercontent.com/107632780/235251926-a3f88b33-7bda-4338-baca-a59db66d6e4c.png)

2023-04-28 21:13 UTC, V-Blaze commented on index.html
> +      <div class="members">
- [ ] You did great populating the content of this section dynamically but I think you also need to follow the design specifications here. :+1: Also this section is the `Featured Speakers` section and not `Members` Please look into this. :+1: :smile: 

Your design:
![Screenshot from 2023-04-28 21-51-49](https://user-images.githubusercontent.com/107632780/235252456-bc8db390-9d9d-4121-a3f8-3ee35a3f3467.png)

Given design:
![Screenshot from 2023-04-28 21-51-34](https://user-images.githubusercontent.com/107632780/235252501-f74216ed-765b-4fc3-a94c-2ce8f174df27.png)

2023-04-28 21:13 UTC, V-Blaze commented on index.html
> +  </footer>
- [ ] As I have suggested above, Your footer needs to follow the given design too. The color and the margins need to match. I'll suggest you also look into this. Your ability to deliver a given design is one of the skills that show you are a good software engineer. :smile: :tulip: 

Your design :
![Screenshot from 2023-04-28 21-56-10](https://user-images.githubusercontent.com/107632780/235253155-1ea73d67-b1e1-4a3b-821d-70b7d9a4b047.png)

Provided design:
![Screenshot from 2023-04-28 21-55-48](https://user-images.githubusercontent.com/107632780/235253215-262fb5d9-189b-4ca5-a353-0286659513ce.png)

2023-04-28 21:13 UTC, V-Blaze commented on aboutme.html
> +        <p class="contact-p"> Please, contact us per Email for further questions </p>
- [ ] Just as I have mentioned above, Please go through your About page and implement it closely following the provided design: :wave: :smile: 

Your current design:
![Screenshot from 2023-04-28 22-01-00](https://user-images.githubusercontent.com/107632780/235253660-7bc41934-a24b-4fb8-8c42-eb72c1f1b629.png)

Provided design:
![Screenshot from 2023-04-28 22-00-42](https://user-images.githubusercontent.com/107632780/235253698-d299d3a2-8562-4066-8f70-fa29396e9268.png)

2023-04-28 21:13 UTC, V-Blaze commented on README.md
> +I would like to thank Microverse for the opportunity.
> The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

- [ ] As stated in the project requirement, Please you need to add the proper acknowledgment in your readme file and also correctly link it to the author as it is the best practice to recognize and appreciate other people's creative ideas when we use it. :smile: :+1:

2023-04-29 18:06 UTC, levy002 requested changes
## Hello @Joaquin123455   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


## Highlights
- No linter error :heavy_check_mark: 
- Good UI :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] As requested by the previous reviewer, kindly make sure to edit your PR summary by providing a well-detailed PR summary that explains what changes have been made on this branch instead of copying the project requirements provided by Microverse without changing anything.

- [ ] Kindly record another video presentation because the one you provide has no sound. Please record another and make sure it has sound which will help the next reviewer to understand briefly what you have achieved in your capstone.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 18:06 UTC, levy002 commented on css/desktop.css
> +  }
- [OPTIONAL] Kindly make sure to remove this `See the whole program` button in the mobile version in order to match the provided Behance design.


   - ### YOUR DESIGN
   
  ![image](https://user-images.githubusercontent.com/87197412/235316941-f111398a-3632-4fdc-9d97-8c2da0c0d393.png)

   - ### BEHANCE DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/235316997-0b75e22d-fc62-46c8-9fc6-07559f86439d.png)

2023-04-29 18:06 UTC, levy002 commented on css/stylemenu.css
> +*/
- [OPTIONAL] Kindly make sure to remove all comments in order to keep your codebase clean and professional.

2023-04-29 18:06 UTC, levy002 commented on css/style.css
> +
- [OPTIONAL] Kindly make sure the color of this text and the background color matches exactly the provided one on Behance design.

    - ### YOUR DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/235317194-1c2d32ec-02ac-4538-b377-ca04b0990b9d.png)

    - ### BEHANCE DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/235317217-fc96c815-4a9c-48ab-a2ae-4e5040d13086.png)

2023-04-29 18:06 UTC, levy002 commented on css/style.css
> +}
- [OPTIONAL] KIndly make sure to remove the `padding` in the mobile version of the speakers' section because it will help to align the speakers' section contents with the provided Behance design.

    - ### YOUR DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/235317382-59265eba-0907-42ed-9281-5a6ca3ffb9cb.png)

    - ### FIGMA DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/235317360-d2bb77a8-9a20-4b78-a0a8-ab537efbb87a.png)

2023-04-29 18:35 UTC, IngDavidTM approved these changes
Hi @Joaquin123455  🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this capstone project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
- There are two pages ✅ 
- The speaker's section was generated dynamically using JavaScript ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 18:36 UTC, merged